version: "3"

services:
  express:
    container_name: "express_test"
    build: ./express
    command: "npm run test"
    restart: "unless-stopped"
    ports:
      - "${EXPRESS_PORT}:8000"
    environment:
      ENVIRONMENT_TYPE: "test"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_MAX_CLIENTS: ${POSTGRES_MAX_CLIENTS}

  postgres:
    container_name: "postgres_test"
    image: "postgres:15.4-alpine"
    restart: "unless-stopped"
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    volumes:
      - ./postgres/:/docker-entrypoint-initdb.d/