services:
  express:
    build:
      context: ./express
      args:
        CONNECTION_STRING: "postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/ctf"
    command: "./startup.sh"
    container_name: "express"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ENVIRONMENT_TYPE: "production"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - ctf-network
    restart: "unless-stopped"
    volumes:
      - file-data:/files

  nginx:
    build: ./nginx
    container_name: "nginx"
    depends_on:
      express:
        condition: service_started
      vue:
        condition: service_started
    environment:
      NGINX_SERVER_NAME: ${NGINX_SERVER_NAME}
    networks:
      - ctf-network
    ports:
      - "80:80"
      - "443:443"

  postgres:
    container_name: "postgres"
    environment:
      POSTGRES_DB: "ctf"
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: "postgres"
    healthcheck:
      interval: 5s
      retries: 10
      test: [ "CMD-SHELL", "pg_isready -d ctf -U postgres" ]
      timeout: 5s
    image: "postgres:16-alpine"
    networks:
      - ctf-network
    restart: "unless-stopped"
    volumes:
      - db-data:/var/lib/postgresql/data

  vue:
    container_name: "vue"
    build: ./vue
    command: "CMD http-server dist -p 8000"
    depends_on:
      express:
        condition: service_started
    environment:
      VITE_API_URL: "https://${NGINX_SERVER_NAME}/api"
    networks:
      - ctf-network

networks:
  ctf-network:
    driver: bridge

volumes:
  db-data:
  file-data: