version: "3"

services:
  astro:
    container_name: "astro"
    build: ./astro
    restart: "unless-stopped"
    depends_on:
      express:
        condition: service_healthy
    ports:
      - "${ASTRO_PORT}:4321"

  express:
    container_name: "express"
    build: ./express
    command: "npm run start"
    restart: "unless-stopped"
    depends_on:
      postgres:
        condition: service_completed_successfully
    ports:
      - "${EXPRESS_PORT}:8000"
    environment:
      ENVIRONMENT_TYPE: "production"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_MAX_CLIENTS: ${POSTGRES_MAX_CLIENTS}
      POSTGRES_URL: "postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres"

  postgres:
    container_name: "postgres"
    image: "postgres:15.4-alpine"
    restart: "unless-stopped"
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    volumes:
      - ./postgres/:/docker-entrypoint-initdb.d/
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
