version: "3"

services:
  astro:
    build: ./astro
    command: "npm run dev -- --host 0.0.0.0 --verbose"
    container_name: "astro"
    depends_on:
      express:
        condition: service_started
    networks:
      - ctf-network
    ports:
      - "${ASTRO_PORT}:4321"
    restart: "unless-stopped"

  express:
    build:
      context: ./express
      args:
        CONNECTION_STRING: "postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/ctf"
    command: "./startup.sh"
    container_name: "express"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ENVIRONMENT_TYPE: "development"
      POSTGRES_MAX_CLIENTS: ${POSTGRES_MAX_CLIENTS}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - ctf-network
    ports:
      - "8000:8000"
    restart: "unless-stopped"

  postgres:
    container_name: "postgres"
    environment:
      POSTGRES_DB: "ctf"
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      interval: 5s
      retries: 10
      test: [ "CMD", "pg_isready" ]
      timeout: 5s
    image: "postgres:16-alpine"
    networks:
      - ctf-network
    ports:
      - "5432:5432"
    restart: "unless-stopped"
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  ctf-network:
    driver: bridge

volumes:
  db-data: