services:
  express__test:
    build:
      context: ./express
      args:
        CONNECTION_STRING: "postgres://postgres:${POSTGRES_PASSWORD}@postgres__test:5432/ctf"
    command: "./startup.sh"
    container_name: "express__test"
    depends_on:
      postgres__test:
        condition: service_healthy
    environment:
      ENVIRONMENT_TYPE: "test"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - ctf-network
    restart: "no"

  postgres__test:
    container_name: "postgres__test"
    environment:
      POSTGRES_DB: "ctf"
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: "postgres"
    healthcheck:
      interval: 5s
      retries: 10
      test: [ "CMD-SHELL", "pg_isready -d ctf -U postgres" ]
      timeout: 5s
    image: "postgres:16-alpine"
    networks:
      - ctf-network
    ports:
      - "5432:5432"
    restart: "no"

networks:
  ctf-network:
    driver: bridge