version: "3"

services:
  express:
    build:
      context: ./express
      args:
        CONNECTION_STRING: "postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/ctf"
    command: "./startup.sh"
    container_name: "express"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ENVIRONMENT_TYPE: "development"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - ctf-network
    restart: "unless-stopped"

  nginx:
    build: ./nginx
    container_name: "nginx"
    depends_on:
      express:
        condition: service_started
      vue:
        condition: service_started
    environment:
      NGINX_SERVER_NAME: ${NGINX_SERVER_NAME}
    networks:
      - ctf-network
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
      - "8001:8001"

  postgres:
    container_name: "postgres"
    environment:
      POSTGRES_DB: "ctf"
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      interval: 5s
      retries: 10
      test: [ "CMD", "pg_isready" ]
      timeout: 5s
    image: "postgres:16-alpine"
    networks:
      - ctf-network
    ports:
      - "5432:5432"
    restart: "unless-stopped"
    volumes:
      - db-data:/var/lib/postgresql/data

  vue:
    container_name: "vue"
    build: ./vue
    command: "npm run dev -- --host"
    depends_on:
      express:
        condition: service_started
    environment:
      VITE_API_URL: "http://localhost:8001"
    networks:
      - ctf-network

networks:
  ctf-network:
    driver: bridge

volumes:
  db-data: